import { jsPDF } from "jspdf";
import { dateTime, money } from "./format";

type Tx = {
  reference: string;
  category: string;
  direction: string;
  amount: number | string;
  status: string;
  description: string | null;
  recipient_name: string | null;
  recipient_bank: string | null;
  recipient_account: string | null;
  created_at: string;
};

export function downloadReceipt(tx: Tx, currency = "USD") {
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  doc.setFillColor(122, 32, 32);
  doc.rect(0, 0, 595, 110, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text("Wellspring Bank", 40, 55);
  doc.setFontSize(10);
  doc.text("Simulated transaction receipt — no real funds involved", 40, 76);

  doc.setTextColor(30, 30, 30);
  doc.setFontSize(16);
  doc.text(
    `${tx.direction === "credit" ? "+" : "-"}${money(Number(tx.amount), currency)}`,
    40,
    150,
  );

  const rows: [string, string][] = [
    ["Reference", tx.reference],
    ["Type", tx.category.replace(/_/g, " ")],
    ["Direction", tx.direction],
    ["Status", tx.status],
    ["Date / Time", dateTime(tx.created_at)],
    ["Description", tx.description ?? "—"],
    ["Recipient", tx.recipient_name ?? "—"],
    ["Bank", tx.recipient_bank ?? "—"],
    ["Account", tx.recipient_account ?? "—"],
  ];

  let y = 190;
  doc.setFontSize(11);
  for (const [label, value] of rows) {
    doc.setTextColor(120, 120, 120);
    doc.text(label, 40, y);
    doc.setTextColor(20, 20, 20);
    doc.text(String(value), 220, y);
    y += 26;
  }

  doc.setDrawColor(220, 220, 220);
  doc.line(40, y + 6, 555, y + 6);
  doc.setTextColor(140, 140, 140);
  doc.setFontSize(9);
  doc.text("This document is generated by a fictional banking demo application.", 40, y + 28);

  doc.save(`receipt-${tx.reference}.pdf`);
}
